import React, { useState } from 'react';
import { Loader2 } from 'lucide-react';

export default function PDFExport({ results, filename, viewerInstance }) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = () => {
    if (!results) {
      alert("No data available to export.");
      return;
    }
    
    setIsExporting(true);

    // Let the UI update before generating PDF
    setTimeout(async () => {
      try {
        const { jsPDF } = await import('jspdf');
        
        // Dynamically import autotable and attach it
        const autoTableModule = await import('jspdf-autotable');
        const autoTable = autoTableModule.default || autoTableModule;

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;
        
        // Header
        doc.setFontSize(22);
        doc.setTextColor(33, 43, 54);
        doc.text("Protein Analysis Report", 14, 22);
        
        doc.setFontSize(11);
        doc.setTextColor(100, 116, 139);
        doc.text(`Generated by FoldSight Analytics`, 14, 30);
        
        // Protein Identity
        doc.setFontSize(14);
        doc.setTextColor(33, 43, 54);
        doc.text("Protein Identity", 14, 45);
        
        doc.setFontSize(10);
        doc.setTextColor(71, 85, 105);
        doc.text(`Name: ${results.protein_name || 'Unknown'}`, 14, 52);
        doc.text(`Identifier: ${results.uniprot_id || 'Custom Sequence'}`, 14, 58);
        
        const seqLen = results.properties?.length || results.sequence?.length || 0;
        doc.text(`Sequence Length: ${seqLen} AA`, 14, 64);

        // Scientific Interpretation
        let currentY = 76;
        if (results.scientific_summary) {
          doc.setFontSize(14);
          doc.setTextColor(33, 43, 54);
          doc.text("Scientific Interpretation", 14, currentY);
          currentY += 8;
          
          doc.setFontSize(10);
          doc.setTextColor(71, 85, 105);
          
          const sum = results.scientific_summary;
          const sections = [
            { title: "Overview", text: typeof sum === 'object' ? (sum.overview || '') : (sum || '') },
            { title: "Structural Assessment", text: typeof sum === 'object' ? (sum.structural || '') : '' },
            { title: "Biological Interpretation", text: typeof sum === 'object' ? (sum.biological || '') : '' }
          ];

          sections.forEach(sec => {
            if (sec.text) {
              doc.setFont(undefined, 'bold');
              doc.text(sec.title + ":", 14, currentY);
              doc.setFont(undefined, 'normal');
              const lines = doc.splitTextToSize(sec.text.toString(), pageWidth - 28);
              currentY += 5;
              doc.text(lines, 14, currentY);
              currentY += (lines.length * 5) + 4;
            }
          });
        }

        // Physicochemical Properties Table
        if (results.properties) {
          currentY += 5;
          doc.setFontSize(14);
          doc.setTextColor(33, 43, 54);
          doc.text("Physicochemical Properties", 14, currentY);
          
          const safeNum = (num, decimals = 2) => num != null ? Number(num).toFixed(decimals) : 'N/A';
          const mw = results.properties.molecular_weight ? safeNum(results.properties.molecular_weight / 1000, 2) + ' kDa' : 'N/A';

          const propsData = [
            ['Molecular Weight', mw],
            ['Isoelectric Point (pI)', safeNum(results.properties.pi)],
            ['Instability Index', safeNum(results.properties.instability_index, 1)],
            ['Stability', results.properties.stability || 'N/A'],
            ['Aliphatic Index', safeNum(results.properties.aliphatic_index, 1)],
            ['GRAVY Score', safeNum(results.properties.gravy, 3)],
            ['Solubility', results.properties.solubility || 'N/A'],
            ['Extinction Coefficient', results.properties.extinction_coef_reduced || 'N/A'],
            ['In Vitro Half-Life', results.properties.half_life || 'N/A']
          ];

          autoTable(doc, {
            startY: currentY + 5,
            head: [['Metric', 'Value']],
            body: propsData,
            theme: 'grid',
            headStyles: { fillColor: [47, 62, 70] },
            styles: { fontSize: 10, cellPadding: 3 }
          });
          currentY = doc.lastAutoTable.finalY + 15;
        }
        
        // Structural Architecture
        if (results.alphafold) {
          // Prevent writing off the bottom of the page
          if (currentY > 250) {
            doc.addPage();
            currentY = 20;
          }
          
          doc.setFontSize(14);
          doc.setTextColor(33, 43, 54);
          doc.text("Structural Predictions (AlphaFold)", 14, currentY);
          currentY += 8;
          
          doc.setFontSize(10);
          doc.setTextColor(71, 85, 105);
          const plddtGlobal = results.alphafold.plddt?.global;
          doc.text(`Global pLDDT (Confidence): ${plddtGlobal != null ? Number(plddtGlobal).toFixed(1) : '0.0'}%`, 14, currentY);
          currentY += 6;
          
          const domains = results.alphafold.pae?.domains || [];
          doc.text(`Rigid Domains Identified: ${domains.length}`, 14, currentY);
          currentY += 6;
          
          domains.forEach((dom, i) => {
            doc.text(`  Domain ${i + 1}: Residues ${dom[0]} - ${dom[1]}`, 14, currentY);
            currentY += 5;
          });
        }
        
        // Render 3D Model Snapshot
        if (viewerInstance) {
          const proteinImg = viewerInstance.pngURI();
          if (proteinImg) {
            if (currentY > 160) {
              doc.addPage();
              currentY = 20;
            } else {
              currentY += 15;
            }
            
            doc.setFontSize(14);
            doc.setTextColor(33, 43, 54);
            doc.text("3D Molecular Structure", 14, currentY);
            currentY += 10;
            
            // Draw image with approximate 4:3 aspect ratio (160x120 mm)
            doc.addImage(proteinImg, 'PNG', 14, currentY, 160, 120);
          }
        }

        doc.save(filename || 'protein_analysis_report.pdf');
      } catch (error) {
        console.error("PDF Export failed:", error);
        alert("Failed to export PDF report. Check console for details.");
      } finally {
        setIsExporting(false);
      }
    }, 50);
  };

  return (
    <button 
      onClick={handleExport}
      disabled={isExporting || !results}
      className="btn-outline !text-sm !py-1.5"
      title="Export Publication-Quality PDF"
    >
      {isExporting ? (
        <Loader2 size={16} className="animate-spin inline-block mr-1.5" />
      ) : (
        <span className="material-symbols-outlined text-[16px] mr-1.5 align-text-bottom">download</span>
      )}
      EXPORT PDF
    </button>
  );
}
