import React, { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export default function PDFExport({ results, filename }) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = () => {
    if (!results) {
      alert("No data available to export.");
      return;
    }
    
    setIsExporting(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.width;
      
      // Header
      doc.setFontSize(22);
      doc.setTextColor(33, 43, 54);
      doc.text("Protein Analysis Report", 14, 22);
      
      doc.setFontSize(11);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by FoldSight Analytics`, 14, 30);
      
      // Protein Identity
      doc.setFontSize(14);
      doc.setTextColor(33, 43, 54);
      doc.text("Protein Identity", 14, 45);
      
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105);
      doc.text(`Name: ${results.protein_name || 'Unknown'}`, 14, 52);
      doc.text(`Identifier: ${results.uniprot_id || 'Custom Sequence'}`, 14, 58);
      doc.text(`Sequence Length: ${results.properties?.length || results.sequence?.length || 0} AA`, 14, 64);

      // Scientific Interpretation
      let currentY = 76;
      if (results.scientific_summary) {
        doc.setFontSize(14);
        doc.setTextColor(33, 43, 54);
        doc.text("Scientific Interpretation", 14, currentY);
        currentY += 8;
        
        doc.setFontSize(10);
        doc.setTextColor(71, 85, 105);
        
        const sum = results.scientific_summary;
        const sections = [
          { title: "Overview", text: typeof sum === 'object' ? sum.overview : sum },
          { title: "Structural Assessment", text: typeof sum === 'object' ? sum.structural : '' },
          { title: "Biological Interpretation", text: typeof sum === 'object' ? sum.biological : '' }
        ];

        sections.forEach(sec => {
          if (sec.text) {
            doc.setFont(undefined, 'bold');
            doc.text(sec.title + ":", 14, currentY);
            doc.setFont(undefined, 'normal');
            const lines = doc.splitTextToSize(sec.text, pageWidth - 28);
            currentY += 5;
            doc.text(lines, 14, currentY);
            currentY += (lines.length * 5) + 4;
          }
        });
      }

      // Physicochemical Properties Table
      if (results.properties) {
        currentY += 5;
        doc.setFontSize(14);
        doc.setTextColor(33, 43, 54);
        doc.text("Physicochemical Properties", 14, currentY);
        
        const propsData = [
          ['Molecular Weight', `${(results.properties.molecular_weight / 1000).toFixed(2)} kDa`],
          ['Isoelectric Point (pI)', results.properties.pi?.toFixed(2)],
          ['Instability Index', results.properties.instability_index?.toFixed(1) || 'N/A'],
          ['Stability', results.properties.stability || 'N/A'],
          ['Aliphatic Index', results.properties.aliphatic_index?.toFixed(1) || 'N/A'],
          ['GRAVY Score', results.properties.gravy?.toFixed(3) || 'N/A'],
          ['Solubility', results.properties.solubility || 'N/A'],
          ['Extinction Coefficient', results.properties.extinction_coef_reduced || 'N/A'],
          ['In Vitro Half-Life', results.properties.half_life || 'N/A']
        ];

        doc.autoTable({
          startY: currentY + 5,
          head: [['Metric', 'Value']],
          body: propsData,
          theme: 'grid',
          headStyles: { fillColor: [47, 62, 70] },
          styles: { fontSize: 10, cellPadding: 3 }
        });
        currentY = doc.lastAutoTable.finalY + 15;
      }
      
      // Structural Architecture
      if (results.alphafold) {
        doc.setFontSize(14);
        doc.setTextColor(33, 43, 54);
        doc.text("Structural Predictions (AlphaFold)", 14, currentY);
        currentY += 8;
        
        doc.setFontSize(10);
        doc.setTextColor(71, 85, 105);
        doc.text(`Global pLDDT (Confidence): ${results.alphafold.plddt?.global?.toFixed(1) || 0}%`, 14, currentY);
        currentY += 6;
        
        const domains = results.alphafold.pae?.domains || [];
        doc.text(`Rigid Domains Identified: ${domains.length}`, 14, currentY);
        currentY += 6;
        
        domains.forEach((dom, i) => {
          doc.text(`  Domain ${i + 1}: Residues ${dom[0]} - ${dom[1]}`, 14, currentY);
          currentY += 5;
        });
      }

      doc.save(filename || 'protein_analysis_report.pdf');
    } catch (error) {
      console.error("PDF Export failed", error);
      alert("Failed to export PDF report. Check console for details.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <button 
      onClick={handleExport}
      disabled={isExporting || !results}
      className={`action-button secondary flex items-center gap-2 ${!results ? 'opacity-50 cursor-not-allowed' : ''}`}
      title="Export Publication-Quality PDF"
    >
      {isExporting ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
      <span>Export PDF</span>
    </button>
  );
}
